// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/

import java.util.List;
import java.util.Map;

/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Map<Integer, Tile> tilesById;
	/**
	 * 
	 */
	private Map<Integer, Node> nodesById;
	/**
	 * 
	 */
	private Map<Integer, Path> pathsById;
	/**
	 * 
	 */
	private Map<Integer, List<Path>> pathsByNodeId;
	/**
	 * 
	 */
	private List<Tile> tiles;
	/**
	 * 
	 */
	private List<Node> ndoes;
	/**
	 * 
	 */
	private List<Path> paths;
	/**
	 * 
	 */
	public Node[] node;

	/**
	 * 
	 */
	public Board(List<Tile> tiles, List<Node> nodes, List<Path> paths) {
	}

	/**
	 * 
	 */
	public void indexById() {
	}

	/**
	 * 
	 */
	public void buildPathAdjacency() {
    }

	/**
	 * 
	 */
	public void validateAdjacency() {
	}

	/**
	 * 
	 */
	public List<Tile> getTiles() {
        return List.of();
    }

	/**
	 * 
	 */
	public List<Node> getNodes() {
        return List.of();
    }

	/**
	 * 
	 */
	public List<Path> getPaths() {
        return List.of();
    }

	/**
	 * 
	 */
	public Node getNode() {
        return null;
    }

	/**
	 * 
	 */
	public Path getPath() {
        return null;
    }

	/**
	 * 
	 */
	public List<Path> pathsAdjacentToNode() {
        return List.of();
    }

	/**
	 * 
	 */
	public List<Tile> tilesForRoll() {
        return List.of();
    }
}
