// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/*
 * Flyweight building object with only intrinsic state.
 * Node keeps owner as extrinsic state.
 */
public final class Building {
    private static final Building EMPTY = new Building(BuildingType.NONE, 0);
    private static final Building SETTLEMENT = new Building(BuildingType.SETTLEMENT, 1);
    private static final Building CITY = new Building(BuildingType.CITY, 2);

    private final BuildingType type;
    private final int productionYield;

    private Building(BuildingType type, int productionYield) {
        this.type = type;
        this.productionYield = productionYield;
    }

    public static Building empty() {
        return EMPTY;
    }

    public static Building settlement() {
        return SETTLEMENT;
    }

    public static Building city() {
        return CITY;
    }

    public static Building of(BuildingType type) {
        return switch (type) {
            case NONE -> EMPTY;
            case SETTLEMENT -> SETTLEMENT;
            case CITY -> CITY;
        };
    }

    public BuildingType getType() {
        return type;
    }

    public boolean isOccupied() {
        return type != BuildingType.NONE;
    }

    public int productionYield() {
        return productionYield;
    }
}
