// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Building {
	/**
	 * 
	 */
	private BuildingType type;
	/**
	 * 
	 */
	private Player owner;

	/**
	 * 
	 */
	public Building(BuildingType type, Player owner) {
	}

	/**
	 * 
	 */
	public static void empty() {
	}

	/**
	 * 
	 */
	public static void settlement() {
	}

	/**
	 * 
	 */
	public static void city() {
	}

	/**
	 * 
	 */
	public void getType() {
	}

	/**
	 * 
	 */
	public void productionYield() {
	}
}
