// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Demonstrator {
	/**
	 * 
	 */
	private static Board buildFullBoard() {
        return null;
    }
}
