// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Path {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Node nodeA;
	/**
	 * 
	 */
	private Node nodeB;
	/**
	 * 
	 */
	private Player owner;

	/**
	 * 
	 */
	public Path(int id, int nodeAId, int nodeBId) {
	}

	/**
	 * 
	 */
	public int getId() {
        return 0;
    }

	/**
	 * 
	 */
	public int getNodeAId() {
        return 0;
    }

	/**
	 * 
	 */
	public int getNodeBId() {
        return 0;
    }

	/**
	 * 
	 */
	public boolean isOwnedBy() {
        return false;
    }

	/**
	 * 
	 */
	public void claim(Player player) {
	}

	/**
	 *
	 */
	public boolean canBuildRoad(Board board, Player player) {
        return false;
    }

	/**
	 * 
	 */
	private boolean canExtendFromNode(Board board, Player player, int nodeId) {
        return false;
    }
}
