// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
/*
 * The five types of resources that can be collected and spent.
 */
public enum ResourceType {
    WOOD,
    BRICK,
    SHEEP,
    WHEAT,
    ORE
}
