// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class ActionDecision {
	/**
	 * 
	 */
	private BuildAction action;
	/**
	 * 
	 */
	private int targetId;

	/**
	 * 
	 * @param action 
	 * @param targetId 
	 */
	private ActionDecision(BuildAction action, int targetId) {
	}

	/**
	 * 
	 */
	public static ActionDecision None() {
		return new ActionDecision();
	}

	/**
	 * 
	 * @param pathId 
	 */
	public static ActionDecision road(int pathId) {
		return null;
	}

	/**
	 * 
	 * @param nodeId 
	 */
	public static ActionDecision settlement(int nodeId) {
		return null;
	}

	/**
	 * 
	 * @param nodeId 
	 */
	public static ActionDecision city(int nodeId) {
		return null;
	}

	/**
	 * 
	 */
	public BuildAction getAction() {
        return null;
    }

	/**
	 * 
	 */
	public int getTargetId() {
        return 0;
    }
}
