// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/

import java.util.List;
import java.util.Map;

/**
 * 
 */
public class BuildPlanner {
	/**
	 * 
	 */
	private static Map<ResourceType, Integer> SETTLEMENT_COST;
	/**
	 * 
	 */
	private static Map<ResourceType, Integer> ROAD_COST;
	/**
	 * 
	 */
	private static Map<ResourceType, Integer> CITY_COST;

	/**
	 * 
	 */
	public BuildPlanner() {
	}

	/**
	 * 
	 * @param board 
	 * @param player 
	 */
	public static List<ActionDecision> availableActions(Board board, Player player) {
        return List.of();
    }

	/**
	 * 
	 */
	public static Map<ResourceType, Integer> settlementCost() {
        return Map.of();
    }

	/**
	 * 
	 */
	public static Map<ResourceType, Integer> roadCost() {
        return Map.of();
    }

	/**
	 * 
	 */
	public static Map<ResourceType, Integer> cityCost() {
        return Map.of();
    }
}
