// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class DiceSet {
	/**
	 * 
	 */
	private Dice Dice1;
	/**
	 * 
	 */
	private Dice Dice2;

	/**
	 * 
	 */
	public DiceSet() {
	}

	/**
	 * 
	 */
	public int nextRoll() {
        return 0;
    }
}
