// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class GameState {
	/**
	 * 
	 */
	private Board board;

	/**
	 * 
	 */
	public void getBoard() {
	}

	/**
	 * 
	 */
	public GameState(Board board) {
	}
}
