// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/

import java.util.List;

/**
 * 
 */
public class GameEngine {
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private List<Player> players;
	/**
	 * 
	 */
	private DiceSet diceSet;
	/**
	 * 
	 */
	private Player longestRoadHolder;
	/**
	 * 
	 */
	private int currentMaxRoadLength;

	/**
	 * 
	 * @param board 
	 * @param players 
	 */
	public GameEngine(Board board, List<Player> players) {
	}

	/**
	 * 
	 */
	public void rollDice() {
	}

	/**
	 * 
	 * @param rounds 
	 */
	public void runSimulation(int rounds) {
	}

	/**
	 * 
	 * @param roll 
	 * @param log 
	 * @param preferredActions 
	 */
	private void distributeResources(int roll, List<String> log, BuildAction preferredActions) {
	}

	/**
	 * 
	 * @param roll 
	 * @param log 
	 */
	private void executeBuildPhase(int roll, List<String> log) {
	}

	/**
	 * 
	 * @param player 
	 * @param action 
	 * @param log 
	 */
	private void applyAction(Player player, ActionDecision action, List<String> log) {
	}

	/**
	 * 
	 * @param player 
	 * @param log 
	 * @param nodeId 
	 */
	private void buildCity(Player player, List<String> log, int nodeId) {
	}

	/**
	 * 
	 * @param nodeId 
	 * @param log 
	 * @param player 
	 */
	private void buildSettlement(int nodeId, List<String> log, Player player) {
	}

	/**
	 * 
	 * @param pathId 
	 * @param log 
	 * @param player 
	 */
	private void buildRoad(int pathId, List<String> log, Player player) {
	}

	/**
	 * 
	 * @param log 
	 * @param player 
	 */
	private void updateLongestRoad(List<String> log, Player player) {
	}

	/**
	 * 
	 * @param rounds 
	 * @param log 
	 */
	private void logRoundVictoryPoints(int rounds, List<String> log) {
	}

	/**
	 * 
	 * @param player 
	 * @param path 
	 */
	private boolean isRoadConnectedToPlayerNetwork(Player player, Path path) {
        return false;
    }

	/**
	 * 
	 * @param player 
	 * @param path 
	 * @param nodeId 
	 */
	private boolean canConnectAtNode(Player player, Path path, int nodeId) {
        return false;
    }
}
