// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/

import java.util.Set;

/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Set<Integer> adjacentTileIds;
	/**
	 * 
	 */
	private Set<Integer> adjacentNodeIds;
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Building building;

	/**
	 * 
	 */
	public Node(int id, Set<Integer> adjacentTileIds, Set<Integer> adjacentNodeIds) {
	}

	/**
	 * 
	 * @param Board 
	 * @param player 
	 */
	public boolean canBuildSettlement(Board Board, Player player) {
        return false;
    }

	/**
	 * 
	 */
	public int getId() {
        return 0;
    }

	/**
	 * 
	 */
	public Set<Integer> getAdjacentTileIds() {
        return Set.of();
    }

	/**
	 * 
	 */
	public void getOwner() {
	}

	/**
	 * 
	 */
	public void isClaimed() {
	}

	/**
	 * 
	 * @param player 
	 */
	public void isOwnedby(Player player) {
	}

	/**
	 * 
	 * @param player 
	 */
	public void claim(Player player) {
	}

	/**
	 * 
	 */
	public void getBuilding() {
	}

	/**
	 * 
	 * @param player 
	 */
	public void upgradeToCity(Player player) {
	}
}
