// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Path {
	/**
	 * 
	 */
	public int id;
	/**
	 * 
	 */
	public Node a;
	/**
	 * 
	 */
	public Node b;
	/**
	 * 
	 */
	public undef Property1;
}
