// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/

import java.util.EnumMap;
import java.util.Map;
import java.util.Set;

/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private EnumMap<ResourceType, Integer> resource;
	/**
	 * 
	 */
	private Set<Integer> settlementNodeIds;
	/**
	 * 
	 */
	private Set<Integer>  cityNodeIds;
	/**
	 * 
	 */
	private Set<Integer> roadNodeIds;
	/**
	 * 
	 */
	private boolean hasLongestRoad;

	/**
	 * 
	 */
	public Player(String name) {
	}

	/**
	 * 
	 */
	public static String requireName(String name) {
        return name;
    }

	/**
	 * 
	 */
	public  String getName() {
        return "";
    }

	/**
	 * 
	 */
	public int getResourceCount() {
        return 0;
    }

	/**
	 * 
	 */
	public Map<ResourceType, Integer> getResources() {
        return Map.of();
    }

	/**
	 * 
	 */
	public int getTotalResourceCount() {
        return 0;
    }

	/**
	 * 
	 */
	public boolean canAfford() {
        return false;
    }

	/**
	 * 
	 */
	public void spend() {
	}

	/**
	 * 
	 */
	public void addSettlement(int nodeId) {
	}

	/**
	 * 
	 */
	public void addCity(int nodeId) {
	}

	/**
	 * 
	 */
	public void addRoad(int pathId) {
	}

	/**
	 * 
	 */
	public void getSettlementNodeIds() {
	}

	/**
	 * 
	 */
	public void getRoadPathIds() {
	}

	/**
	 * 
	 */
	public void getCityNodeIds() {
	}

	/**
	 * 
	 */
	public void setHasLongestRoad() {
	}

	/**
	 * 
	 */
	public int getVictoryPoints() {
        return 0;
    }

	/**
	 * 
	 */
	public int calculateLongestRoad() {
        return 0;
    }

	/**
	 * 
	 */
	public int walkRoad() {
        return 0;
    }
}
