// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/

import java.util.Set;

/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private ResourceType resourceType;
	/**
	 * 
	 */
	private int numberToken;
	/**
	 * 
	 */
	private Set<Integer> adjacentNodeIds;

	/**
	 * 
	 */
	public Tile(int id, ResourceType resourceType, int numberToken, Set<Integer> adjacentNodeIds) {
	}

	/**
	 * 
	 */
	public int getId() {
        return 0;
    }

	/**
	 * 
	 */
	public  ResourceType getResourceType() {
        return null;
    }

	/**
	 * 
	 */
	public ResourceType getResourceTypeOpt() {
        return null;
    }

	/**
	 * 
	 */
	public int getNumberToken() {
        return 0;
    }

	/**
	 * 
	 */
	public Set<Integer> getAdjacentNodeIds() {
        return Set.of();
    }
}
